//! Native-shaped `gen.config` / `gen.check` file generation.
//!
//! Byte-compatible generators for the two project-scaffolding subcommands,
//! mirroring the pinned upstream (`work/ref/credo` @ `ea1ccb9`; verbatim
//! captures in `work/p6-siblings-probe.md` §7, re-captured live for this
//! module on 2026-09-16):
//!
//! - `gen.config` writes the 229-line default `.credo.exs` (`* creating
//!   .credo.exs`) or reports `File exists: .credo.exs, aborted.`.
//! - `gen.check` with no name prints the `lib/my_first_credo_check.ex`
//!   usage hint; with a name it writes the check template to a file named
//!   LITERALLY after the argument (dots are not mapped to directories) plus
//!   the `requires:`/`checks:` wiring instructions (keeping the upstream
//!   `a exec file` wording byte-preserved), or reports
//!   `File exists: <name>, aborted.`.
//!
//! Every path exits 0, including repeats and the no-args usage, like native.
//!
//! Wiring contract for `main.rs` (the owner wires dispatch; this module only
//! renders and writes):
//!
//! ```ignore
//! mod cmd_gen; // top of main.rs
//!
//! // `gen.config`: the target directory is the process working directory.
//! let cwd = std::env::current_dir().expect("cwd");
//! let (stdout, exit) = cmd_gen::run_gen_config_in(&cwd);
//!
//! // `gen.check`: first positional only (`None` prints the usage hint).
//! let (stdout, exit) = cmd_gen::run_gen_check_in(&cwd, args.first().map(String::as_str));
//! ```
//!
//! The `run_gen_config` / `run_gen_check` shims below operate on the process
//! working directory directly for callers that already run there. Tests must
//! use the `_in` variants with unique temp dirs: process-cwd mutation is
//! unsafe under parallel test execution.
//!
//! Known residuals vs native (byte-match limits of this module):
//!
//! - R-GEN-1: I/O failures (unwritable directory, empty filename) crash
//!   native with an Elixir `File.Error`; this module returns a
//!   `** (File.Error) could not write file "<name>": <detail>` message with
//!   exit 1 instead. The success and repeat shapes are byte-exact.
//! - R-GEN-2: `check_name_for` ports `String.replace(~r/(\A|(.+)\/)
//!   (lib|web)\//)`, the trailing-`.ex` strip, `Macro.camelize/1` and the
//!   trailing underscore drop. Values were verified live against the pinned
//!   checkout (including `a/b/my_check.ex` → `A.B.MyCheck` and the `.exs`
//!   non-strip `lib/deep/nested_thing.exs` → `Deep.NestedThing.exs`).
//!   Exotic inputs (non-ASCII case folding, `-` preserved verbatim) follow
//!   the observed rules, not a full Elixir `Macro` port.
//! - R-GEN-3: an absolute `gen.check` name escapes the target dir via
//!   `Path::join` semantics; native writes relative to the process CWD.
//!   Relative names (the admitted scope) stay inside the target dir.
//! - R-GEN-4: piped plain text only: native `:green`/`:red`/`:bright`
//!   colors are stripped, matching non-TTY captures.

use std::path::Path;

/// Pinned upstream default config (upstream MIT; provenance: generated live
/// via `mix run -e 'File.cd!(dir, fn -> Credo.CLI.main(["gen.config"]) end)'`
/// from `work/ref/credo` @ `ea1ccb9`, `MIX_ENV=dev`, Elixir 1.20.2 / OTP 29).
/// The generated bytes are identical (sha256
/// `46692c5957b48e29d92665f7f220a06e7e76122bfbfcece0e41594723f48e3c6`)
/// to the vendored `compatibility/upstream/credo_default_config.exs`, so the
/// single source of truth is reused here instead of embedding a copy.
pub const DEFAULT_CONFIG: &str = include_str!("../compatibility/upstream/credo_default_config.exs");

/// Pinned upstream custom-check template (upstream MIT; provenance: generated
/// live via `Credo.CLI.main(["gen.check", "Foo.Bar"])` from `work/ref/credo`
/// @ `ea1ccb9`; 58 lines, trailing newline included). Native renders the
/// compile-time `.template.check.ex` through `EEx` with the computed check
/// name; the only interpolation site is the `defmodule` line, so other names
/// substitute exactly that line (see [`render_check_template`]).
const CHECK_TEMPLATE: &str = r#"defmodule Foo.Bar do
  @moduledoc """
    Checks all lines for a given Regex.

    This is fun!
  """

  @explanation [
    check: @moduledoc,
    params: [
      regex: "All lines matching this Regex will yield an issue.",
    ]
  ]
  @default_params [
    regex: ~r/Creeeedo/, # our check will find this line.
  ]

  # you can configure the basics of your check via the `use Credo.Check` call
  use Credo.Check, base_priority: :high, category: :custom, exit_status: 0

  @doc false
  @impl true
  def run(%SourceFile{} = source_file, params) do
    lines = SourceFile.lines(source_file)

    # IssueMeta helps us pass down both the source_file and params of a check
    # run to the lower levels where issues are created, formatted and returned
    issue_meta = IssueMeta.for(source_file, params)

    # we use the `params` parameter and the `Params` module to extract a
    # configuration parameter from `.credo.exs` while also providing a
    # default value
    line_regex = params |> Params.get(:regex, __MODULE__)

    # Finally, we can run our custom made analysis.
    # In this example, we look for lines in source code matching our regex:
    Enum.reduce(lines, [], &process_line(&1, &2, line_regex, issue_meta))
  end

  defp process_line({line_no, line}, issues, line_regex, issue_meta) do
    case Regex.run(line_regex, line) do
      nil -> issues
      matches ->
        trigger = matches |> List.last
        new_issue = issue_for(issue_meta, line_no, trigger)
        [new_issue] ++ issues
    end
  end

  defp issue_for(issue_meta, line_no, trigger) do
    # format_issue/2 is a function provided by Credo.Check to help us format the
    # found issue
    format_issue issue_meta,
      message: "OMG! This line matches our Regexp in @default_params!",
      line_no: line_no,
      trigger: trigger
  end
end
"#;

/// No-args `gen.check` usage hint, byte-exact including the trailing blank
/// line (`UI.puts/1` appends a newline to the iodata's own trailing `\n`).
const NO_ARGS_HINT: &str =
    "Please provide a filename:\n\n  mix credo gen.check lib/my_first_credo_check.ex\n\n";

/// Run `gen.config` against the process working directory.
///
/// See [`run_gen_config_in`] for the test-safe variant.
#[must_use]
pub fn run_gen_config() -> (String, i32) {
    let cwd = match std::env::current_dir() {
        Ok(cwd) => cwd,
        Err(error) => return (format!("cannot read working directory: {error}"), 2),
    };
    run_gen_config_in(&cwd)
}

/// Run `gen.config` against an explicit directory.
///
/// Creates `<dir>/.credo.exs` from [`DEFAULT_CONFIG`] (`* creating
/// .credo.exs`, exit 0) or, when it already exists, reports
/// `File exists: .credo.exs, aborted.` (exit 0) without touching the file.
#[must_use]
pub fn run_gen_config_in(dir: &Path) -> (String, i32) {
    let target = dir.join(".credo.exs");
    match std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&target)
    {
        Ok(mut file) => {
            use std::io::Write as _;
            if let Err(error) = file.write_all(DEFAULT_CONFIG.as_bytes()) {
                return (
                    format!("** (File.Error) could not write file \".credo.exs\": {error}"),
                    1,
                );
            }
            ("* creating .credo.exs\n".to_owned(), 0)
        }
        Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => {
            ("File exists: .credo.exs, aborted.\n".to_owned(), 0)
        }
        Err(error) => (
            format!("** (File.Error) could not write file \".credo.exs\": {error}"),
            1,
        ),
    }
}

/// Run `gen.check` against the process working directory.
///
/// See [`run_gen_check_in`] for the test-safe variant.
#[must_use]
pub fn run_gen_check(name: Option<&str>) -> (String, i32) {
    let cwd = match std::env::current_dir() {
        Ok(cwd) => cwd,
        Err(error) => return (format!("cannot read working directory: {error}"), 2),
    };
    run_gen_check_in(&cwd, name)
}

/// Run `gen.check` against an explicit directory.
///
/// - `None` prints the usage hint (exit 0) and writes nothing.
/// - `Some(name)` writes the check template to a file named LITERALLY
///   `name` (parent directories created, mirroring native `mkdir_p`),
///   prints `* creating <name>` plus the wiring instructions (exit 0),
///   or reports `File exists: <name>, aborted.` (exit 0) without touching
///   the file.
#[must_use]
pub fn run_gen_check_in(dir: &Path, name: Option<&str>) -> (String, i32) {
    let Some(name) = name else {
        return (NO_ARGS_HINT.to_owned(), 0);
    };
    let target = dir.join(name);
    if target.exists() {
        return (format!("File exists: {name}, aborted.\n"), 0);
    }
    if let Some(parent) = target
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        && let Err(error) = std::fs::create_dir_all(parent)
    {
        return (
            format!("** (File.Error) could not write file \"{name}\": {error}"),
            1,
        );
    }
    let check_name = check_name_for(name);
    match std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&target)
    {
        Ok(mut file) => {
            use std::io::Write as _;
            if let Err(error) = file.write_all(render_check_template(&check_name).as_bytes()) {
                return (
                    format!("** (File.Error) could not write file \"{name}\": {error}"),
                    1,
                );
            }
            (created_message(name, &check_name), 0)
        }
        Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => {
            (format!("File exists: {name}, aborted.\n"), 0)
        }
        Err(error) => (
            format!("** (File.Error) could not write file \"{name}\": {error}"),
            1,
        ),
    }
}

/// Map a `gen.check` filename to its check module name, mirroring upstream
/// `check_name_for/1`: strip the leading path through the last `lib/` or
/// `web/` segment, strip a trailing `.ex`, camelize, drop underscores.
#[must_use]
pub fn check_name_for(filename: &str) -> String {
    let stripped = strip_lib_web_prefix(filename);
    let no_ext = stripped.strip_suffix(".ex").unwrap_or(stripped);
    no_ext
        .split('/')
        .map(camelize_segment)
        .collect::<Vec<_>>()
        .join(".")
        .replace('_', "")
}

/// Render the check template for one module name: the only interpolation
/// site in upstream `.template.check.ex` is `defmodule <%= @check_name %>`,
/// so exactly that line is substituted (byte-exact for `Foo.Bar`).
#[must_use]
fn render_check_template(check_name: &str) -> String {
    CHECK_TEMPLATE.replacen(
        "defmodule Foo.Bar do",
        &format!("defmodule {check_name} do"),
        1,
    )
}

/// Success stdout for one created check file, byte-exact (keeps the upstream
/// `a exec file` wording). One literal per line: Rust `\`-continuations
/// would strip the significant leading spaces, so explicit `\n` drives
/// every line break.
#[must_use]
fn created_message(filename: &str, check_name: &str) -> String {
    format!(
        "* creating {filename}\n\nAdd the generated file to the list of `requires` in `.credo.exs`:\n\n    requires: [\"{filename}\"], # <-- add file here\n\nRemember to add the generated module to the list of `checks`:\n\n    checks: [\n      {{{check_name}}}, # <-- add check here\n    ]\n\nIf you do not have a exec file yet, use `mix credo gen.config`\n"
    )
}

/// Strip the leading path through the last `lib/` or `web/` path segment
/// (upstream `String.replace(~r/(\A|(.+)\/)(lib|web)\//, "")` with a greedy
/// middle, so the LAST such segment wins).
#[must_use]
fn strip_lib_web_prefix(filename: &str) -> &str {
    let bytes = filename.as_bytes();
    let mut cut: Option<usize> = None;
    let mut index = 0;
    while index + 4 <= bytes.len() {
        let at_segment = index == 0 || bytes[index - 1] == b'/';
        if at_segment {
            for dir in ["lib/", "web/"] {
                if bytes[index..].starts_with(dir.as_bytes()) {
                    cut = Some(index + dir.len());
                }
            }
        }
        index += 1;
    }
    match cut {
        Some(end) => &filename[end..],
        None => filename,
    }
}

/// One `/`-separated segment through upstream `Macro.camelize/1`: split on
/// `_`, uppercase each part's first character, keep the rest (including
/// case and `-`) verbatim, drop the underscores by joining.
#[must_use]
fn camelize_segment(segment: &str) -> String {
    segment
        .split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};

    /// Process-unique counter so parallel tests never share a directory.
    static NEXT_DIR: AtomicU64 = AtomicU64::new(0);

    /// Fresh unique scratch directory (created, caller-owned, removed by the
    /// test when done). Never touches the process working directory.
    fn unique_dir(tag: &str) -> std::path::PathBuf {
        let id = NEXT_DIR.fetch_add(1, Ordering::SeqCst);
        let dir = std::env::temp_dir().join(format!("qredo-gen-{tag}-{}-{id}", std::process::id()));
        std::fs::create_dir_all(&dir).expect("scratch dir");
        dir
    }

    #[test]
    fn gen_config_creates_default_config_byte_identical() {
        let dir = unique_dir("config");
        let (stdout, exit) = run_gen_config_in(&dir);
        assert_eq!(exit, 0);
        assert_eq!(stdout, "* creating .credo.exs\n");
        let written = std::fs::read_to_string(dir.join(".credo.exs")).expect("config written");
        assert_eq!(written, DEFAULT_CONFIG);
        assert_eq!(written.lines().count(), 229);
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn gen_config_repeat_keeps_existing_file() {
        let dir = unique_dir("config-repeat");
        std::fs::write(dir.join(".credo.exs"), "sentinel\n").expect("seed");
        let (stdout, exit) = run_gen_config_in(&dir);
        assert_eq!(exit, 0);
        assert_eq!(stdout, "File exists: .credo.exs, aborted.\n");
        assert_eq!(
            std::fs::read_to_string(dir.join(".credo.exs")).expect("untouched"),
            "sentinel\n"
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn gen_check_no_args_prints_usage_and_writes_nothing() {
        let dir = unique_dir("check-usage");
        let (stdout, exit) = run_gen_check_in(&dir, None);
        assert_eq!(exit, 0);
        assert_eq!(
            stdout,
            "Please provide a filename:\n\n  mix credo gen.check lib/my_first_credo_check.ex\n\n"
        );
        assert_eq!(stdout.len(), 79);
        let entries: Vec<_> = std::fs::read_dir(&dir).expect("readable").collect();
        assert!(entries.is_empty(), "nothing is created");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn gen_check_foo_bar_creates_literal_file_verbatim() {
        let dir = unique_dir("check-foobar");
        let (stdout, exit) = run_gen_check_in(&dir, Some("Foo.Bar"));
        assert_eq!(exit, 0);
        assert_eq!(stdout.len(), 320);
        assert!(stdout.starts_with("* creating Foo.Bar\n"), "{stdout:?}");
        assert!(
            stdout.contains("    requires: [\"Foo.Bar\"], # <-- add file here\n"),
            "{stdout:?}"
        );
        assert!(
            stdout.contains("      {Foo.Bar}, # <-- add check here\n"),
            "{stdout:?}"
        );
        assert!(
            stdout.ends_with("If you do not have a exec file yet, use `mix credo gen.config`\n"),
            "{stdout:?}"
        );
        let written = std::fs::read_to_string(dir.join("Foo.Bar")).expect("check written");
        assert_eq!(written, CHECK_TEMPLATE);
        assert_eq!(written, render_check_template("Foo.Bar"));
        assert_eq!(written.lines().count(), 58);
        assert!(written.starts_with("defmodule Foo.Bar do\n"), "{written:?}");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn gen_check_repeat_keeps_existing_file() {
        let dir = unique_dir("check-repeat");
        std::fs::write(dir.join("Foo.Bar"), "sentinel\n").expect("seed");
        let (stdout, exit) = run_gen_check_in(&dir, Some("Foo.Bar"));
        assert_eq!(exit, 0);
        assert_eq!(stdout, "File exists: Foo.Bar, aborted.\n");
        assert_eq!(
            std::fs::read_to_string(dir.join("Foo.Bar")).expect("untouched"),
            "sentinel\n"
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn gen_check_renders_check_name_for_lib_paths() {
        let dir = unique_dir("check-named");
        let (stdout, exit) = run_gen_check_in(&dir, Some("lib/my_check.ex"));
        assert_eq!(exit, 0);
        assert!(
            stdout.starts_with("* creating lib/my_check.ex\n"),
            "{stdout:?}"
        );
        assert!(
            stdout.contains("      {MyCheck}, # <-- add check here\n"),
            "{stdout:?}"
        );
        let written =
            std::fs::read_to_string(dir.join("lib/my_check.ex")).expect("nested check written");
        assert!(written.starts_with("defmodule MyCheck do\n"), "{written:?}");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn check_name_mapping_matches_pinned_upstream() {
        // Values verified live against `Credo.CLI.Command.GenCheck`
        // (work/ref/credo @ ea1ccb9).
        for (filename, expected) in [
            ("Foo.Bar", "Foo.Bar"),
            ("lib/my_first_credo_check.ex", "MyFirstCredoCheck"),
            (
                "web/controllers/page_controller.ex",
                "Controllers.PageController",
            ),
            ("lib/foo/bar_baz.ex", "Foo.BarBaz"),
            ("a/b/my_check.ex", "A.B.MyCheck"),
            ("lib/deep/nested_thing.exs", "Deep.NestedThing.exs"),
            ("check.ex", "Check"),
        ] {
            assert_eq!(check_name_for(filename), expected, "{filename}");
        }
    }

    #[test]
    fn default_config_is_the_pinned_upstream_text() {
        assert!(DEFAULT_CONFIG.starts_with(
            "# This file contains the configuration for Credo and you are probably reading\n"
        ));
        assert!(DEFAULT_CONFIG.contains("`mix credo.gen.config`"));
        assert!(DEFAULT_CONFIG.ends_with("}\n"));
    }

    #[test]
    fn process_cwd_shims_exist_with_native_signatures() {
        // Compile-time shape check only: the shims delegate to the `_in`
        // variants and are never called here (cwd mutation is unsafe under
        // parallelism). Assert the function pointers type-check.
        let _: fn() -> (String, i32) = run_gen_config;
        let _: fn(Option<&str>) -> (String, i32) = run_gen_check;
    }
}
